### ISSUE TITLE
FTBFS c-utf8 1.0.0

### ISSUE THREAD

**Issue by jengelh** [c-util/c-utf8#3]
```
[    7s] + cd c-utf8-1.0.0
[    7s] + CONFIG_SHELL=/usr/bin/bash
[    7s] + export CONFIG_SHELL
[    7s] + CFLAGS='-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g'
[    7s] + export CFLAGS
[    7s] + CXXFLAGS='-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g'
[    7s] + export CXXFLAGS
[    7s] + FFLAGS='-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g '
[    7s] + export FFLAGS
[    7s] + FCFLAGS='-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g '
[    7s] + export FCFLAGS
[    7s] + LDFLAGS=-flto=auto
[    7s] + export LDFLAGS
[    7s] + /usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . x86_64-suse-linux --includedir=/usr/include/c-utf8
[    8s] The Meson build system
[    8s] Version: 0.64.1
[    8s] Source dir: /home/abuild/rpmbuild/BUILD/c-utf8-1.0.0
[    8s] Build dir: /home/abuild/rpmbuild/BUILD/c-utf8-1.0.0/x86_64-suse-linux
[    8s] Build type: native build
[    8s] Project name: c-utf8
[    8s] Project version: 1.0.0
[    8s] C compiler for the host machine: cc (gcc 12.2.1 "cc (SUSE Linux) 12.2.1 20221020 [revision 0aaef83351473e8f4eb774f8f999bbe87a4866d7]")
[    8s] C linker for the host machine: cc ld.bfd 2.39.0.20220810-1
[    8s] Host machine cpu family: x86_64
[    8s] Host machine cpu: x86_64
[    8s] Found pkg-config: /usr/bin/pkg-config (1.8.0)
[    8s] Run-time dependency libcstdaux-1 found: YES 1.0.0
[    8s] WARNING: pkgconfig variable 'cflags' not defined for dependency libcstdaux-1.
[    8s] WARNING: pkgconfig variable 'version-scripts' not defined for dependency libcstdaux-1.
[    8s] Build targets in project: 6
[    8s] 
[    8s] c-utf8 1.0.0
[    8s] 
[    8s]   User defined options
[    8s]     auto_features : enabled
[    8s]     bindir        : /usr/bin
[    8s]     buildtype     : plain
[    8s]     datadir       : /usr/share
[    8s]     includedir    : /usr/include/c-utf8
[    8s]     infodir       : /usr/share/info
[    8s]     libdir        : /usr/lib64
[    8s]     libexecdir    : /usr/libexec
[    8s]     localedir     : /usr/share/locale
[    8s]     localstatedir : /var
[    8s]     mandir        : /usr/share/man
[    8s]     prefix        : /usr
[    8s]     sbindir       : /usr/sbin
[    8s]     sharedstatedir: /var/lib
[    8s]     sysconfdir    : /etc
[    8s]     wrap_mode     : nodownload
[    8s] 
[    8s] Found ninja-1.11.1 at /usr/bin/ninja
[    8s] WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
[    8s] + /usr/bin/meson compile -C x86_64-suse-linux -j 16 --verbose -j1
[    8s] ninja: Entering directory `/home/abuild/rpmbuild/BUILD/c-utf8-1.0.0/x86_64-suse-linux'
[    8s] [1/14] cc -Isrc/libcutf8-1.so.0.p -Isrc -I../src -I/usr/include/c-stdaux -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c11 '' -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fPIC -fvisibility=hidden -fno-common -MD -MQ src/libcutf8-1.so.0.p/c-utf8.c.o -MF src/libcutf8-1.so.0.p/c-utf8.c.o.d -o src/libcutf8-1.so.0.p/c-utf8.c.o -c ../src/c-utf8.c
[    8s] FAILED: src/libcutf8-1.so.0.p/c-utf8.c.o 
[    8s] cc -Isrc/libcutf8-1.so.0.p -Isrc -I../src -I/usr/include/c-stdaux -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c11 '' -O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g -fPIC -fvisibility=hidden -fno-common -MD -MQ src/libcutf8-1.so.0.p/c-utf8.c.o -MF src/libcutf8-1.so.0.p/c-utf8.c.o.d -o src/libcutf8-1.so.0.p/c-utf8.c.o -c ../src/c-utf8.c
[    8s] cc: warning: : linker input file unused because linking not done
[    8s] cc: error: : linker input file not found: No such file or directory
[    8s] ninja: build stopped: subcommand failed.
```

The `''` argument looks suspicious. meson(-0.64.1) setup complained that libcstdaux-1 has no cflags (which is neither true nor a problem in general). Is the presence of `''` perhaps the result of meson messing up?

**Comment by dvdhrm** [comment]
> ```
> [    8s] Run-time dependency libcstdaux-1 found: YES 1.0.0
> ```

I suspect you are building c-utf8 with a system-installed c-stdaux? This should be fixed if you update c-stdaux to the latest release.

Note that the upstream recommendation is to bundle the c-util projects into their downstream projects. Distributions are certainly allowed to package the libraries individually. However, the lack of semver-support in meson makes it really cumbersome to specify dependencies properly. A proper fix for the issue you are seeing would likely be to bump the minor-version of c-stdaux and make c-utf8 depend on it.

Is there a particular reason why your distribution chose to package the c-util libraries individually?

Lastly, note that you can also run `meson subprojects download` in your checkout to make meson download the configured subprojects. And then there is some configuration to make meson use subprojects rather than system-dependencies (not sure what it was called, though).

**Comment by jengelh** [comment]
>Is there a particular reason why your distribution chose to package the c-util libraries individually?

https://fedoraproject.org/wiki/Bundled_Libraries

And one point not mentioned there: turnaround time due to (un)granularity of projects that bundle something else. The smallest unit that is individually buildable is the rpmbuild invocation / ninja invocation. Chromium is one of the worst examples with over 50000 individual subtargets; if, say, the skia component fails to build, the entire of chromium is failed, and one has to painstakingly rebuild v8 and the HTTP libs in the next run of rpmbuild even if those components were fine on their own. X11R6 had that problem too - and solved it by splitting libX11, libXext etc.

**Comment by dvdhrm** [comment]
> > Is there a particular reason why your distribution chose to package the c-util libraries individually?
> 
> https://fedoraproject.org/wiki/Bundled_Libraries

I think this ignores many facets of modern dependency handling, especially for languages other than C. But I am not here to convince you, so lets move that aside.

Does a dependency update solve your issues? I will try to bump the c-util versions and push a proper changelog tomorrow.

**Comment by eli-schwartz** [comment]
> However, the lack of semver-support in meson makes it really cumbersome to specify dependencies properly.

Hmm? How so? This really has nothing to do with semver ***at all***.

Meson does, of course, support specifying dependency versions:

```meson
dependency('libcstdaux-1', version: '>=1.1.0')
```

**Comment by dvdhrm** [comment]
> > However, the lack of semver-support in meson makes it really cumbersome to specify dependencies properly.
> 
> Hmm? How so? This really has nothing to do with semver _**at all**_.

Ok.

> Meson does, of course, support specifying dependency versions:
> 
> ```meson
> dependency('libcstdaux-1', version: '>=1.1.0')
> ```

This example would not complain if c-stdaux is >=2.0.0, which under semver could lead to compile-errors (best case), or lead to successful builds with broken ABIs or possible security issues due to API changes that did not break the build (worst case).

**Comment by dvdhrm** [comment]
I pushed the version-bump. Please let me know if this fixes your issues!

**Comment by jengelh** [comment]
Yes, >=1.1.0 did it.
