### ISSUE TITLE
c_utf8_verify violates aliasing rules

### ISSUE THREAD

**Issue by bcressey** [c-util/c-utf8#4]
`gcc` warns about this when building with `-Wstrict-aliasing=2`:
```
[6/18] Compiling C object src/libcutf8-1.so.0.p/c-utf8.c.o
../src/c-utf8.c: In function ‘c_utf8_verify’:
../src/c-utf8.c:120:60: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  120 |                         c_utf8_verify_ascii((const char **)&str, &len);
      |                                                            ^~~~
```

I found this surprising given my limited understanding of the rules, but per [this thread](https://www.spinics.net/lists/gcchelp/msg39064.html):
> `char` and `unsigned char` can alias, but not `char *` and `unsigned char *`.

I ran across this while debugging a failure in `dbus-broker` in Bottlerocket that occurred after rebuilding the distro with GCC 11.3 and 12.2. It was a bit of a journey since I'd expected `-Wstrict-aliasing=3` to warn me about the violation, so I initially ruled out aliasing problems. Here is a [test case](https://godbolt.org/z/7z9vMWPbE) I constructed while trying to work out what was going on, in case it's helpful to observe the different output between GCC 10 and later versions. 

Clearly Fedora has been building `dbus-broker` with GCC 11+ for quite some time and hasn't had this issue. This is because Fedora builds with `-fPIC`, so the call to `c_utf8_verify_ascii` goes through the PLT. Since ELF allows another function to be interposed, GCC is unable to fully optimize `c_utf8_verify` - the replacement function might not violate aliasing rules and trigger undefined behavior.

Bottlerocket builds with `-fPIC` but also includes `-fno-semantic-interposition` in the default build flags. This allows GCC to call the function through a local alias, restoring its ability to optimize based on the undefined behavior.

The easy workaround would be to add `-fno-strict-aliasing` to cflags but I expect there's something more clever that could be done.

**Comment by dvdhrm** [comment]
Thanks for the report!

I think the correct fix is to drop the entire `unsigned char` dance and just use plain `char` everywhere. When actually reading the value, we can do the `unsigned char*` cast to get the unsigned value, rather than whatever `char` is set to.

Regarding Fedora, the c-utf8 code is linked as archive with default visibility (i.e., hidden in dbus-broker), so I don't think it goes via PLT, but should be dso-local. Anyway, the code should be fixed regardless.

**Comment by dvdhrm** [comment]
I hope #5 fixes the issues you are seeing! Let me know if any issues remain.

**Comment by bcressey** [comment]
I've tested out `dbus-broker` after updating the subprojects to include the fixes, and confirmed that everything is working fine.

Thank you!

**Comment by thesamesam** [comment]
Gosh, I wish I'd found this bug sooner - I just went down the exact same path that OP did (https://bugs.gentoo.org/919100)! Thank you for both the analysis & the fix.

Is it possible for a new c-utf8 tag to be made and for it to be pulled into dbus-broker (might be enough to just cherry-pick it on the v1 branch, not sure)? Many thanks.

**Comment by dvdhrm** [comment]
Argh! I now pushed a release and updated the branches. Dependent projects should pull it in automatically. Thanks a lot for reporting this!

**Comment by thesamesam** [comment]
Thank you!
